# Generated by Django 4.2.4 on 2024-10-11 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HttpsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(blank=True, max_length=100, null=True)),
                ('api_path', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Https',
                'verbose_name_plural': 'Https',
            },
        ),
        migrations.CreateModel(
            name='MqttSettings',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('server_name_alias', models.CharField(max_length=45)),
                ('host', models.CharField(max_length=45)),
                ('port', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=45)),
                ('password', models.CharField(blank=True, max_length=45)),
                ('qos', models.IntegerField(choices=[(0, 'At most once (0)'), (1, 'At least once (1)'), (2, 'Exactly once (2)')], default=0)),
                ('keepalive', models.IntegerField(default=60)),
                ('pub_topic', models.CharField(default='default/pub/topic', max_length=255)),
                ('sub_topic', models.CharField(default='default/sub/topic', max_length=255)),
            ],
            options={
                'verbose_name': 'Mqtt',
                'verbose_name_plural': 'Mqtt',
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portname', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_printing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UART',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baudrate', models.IntegerField(choices=[(9600, '9600'), (115200, '115200')])),
                ('parity', models.CharField(choices=[('none', 'None'), ('odd', 'Odd'), ('even', 'Even')], max_length=10)),
                ('databit', models.IntegerField(choices=[(5, '5'), (6, '6'), (7, '7'), (8, '8')])),
                ('stopbit', models.DecimalField(choices=[(1.0, '1'), (1.5, '1.5'), (2.0, '2')], decimal_places=1, max_digits=4)),
                ('CTS', models.BooleanField()),
                ('DTR', models.BooleanField()),
                ('XON', models.BooleanField()),
                ('comport', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configuration.port')),
            ],
        ),
    ]
