# Generated by Django 4.2.4 on 2024-07-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_token', models.CharField(blank=True, max_length=100, null=True)),
                ('api_path', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MqttSettings',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('server_name_alias', models.CharField(max_length=45)),
                ('host', models.CharField(max_length=45)),
                ('port', models.IntegerField()),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('qos', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='MQTT',
        ),
    ]
