# Generated by Django 4.2.4 on 2024-07-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_httpssettings_mqttsettings_delete_mqtt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='httpssettings',
            options={'verbose_name': 'Https', 'verbose_name_plural': 'Https'},
        ),
        migrations.AlterModelOptions(
            name='mqttsettings',
            options={'verbose_name': 'Mqtt', 'verbose_name_plural': 'Mqtt'},
        ),
    ]
