# Generated by Django 4.2.4 on 2024-07-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_alter_httpssettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttsettings',
            name='keepalive',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='mqttsettings',
            name='qos',
            field=models.IntegerField(choices=[(0, 'At most once (0)'), (1, 'At least once (1)'), (2, 'Exactly once (2)')], default=0),
        ),
    ]
