# Generated by Django 4.2.4 on 2024-08-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_alter_mqttsettings_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttsettings',
            name='pub_topic',
            field=models.CharField(default='default/pub/topic', max_length=255),
        ),
        migrations.AddField(
            model_name='mqttsettings',
            name='sub_topic',
            field=models.CharField(default='default/sub/topic', max_length=255),
        ),
    ]
