# Generated by Django 4.2.4 on 2024-07-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_devicedetails_machinedetails_machinegroup_and_more'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgroup',
            name='machines',
            field=models.ManyToManyField(related_name='machinesList', to='devices.machinedetails'),
        ),
    ]
