# Generated by Django 4.2.4 on 2024-07-16 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.CharField(default=uuid.uuid1, max_length=15, unique=True)),
                ('model', models.CharField(max_length=10)),
                ('hardwareVersion', models.CharField(max_length=10)),
                ('softwareVersion', models.CharField(max_length=10)),
                ('devicePassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UnRegisteredDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.UUIDField()),
                ('deviceID', models.CharField(default=uuid.uuid1, max_length=15, unique=True)),
                ('model', models.CharField(blank=True, max_length=10, null=True)),
                ('hardwareVersion', models.CharField(blank=True, max_length=10, null=True)),
                ('softwareVersion', models.CharField(blank=True, max_length=10, null=True)),
                ('devicePassword', models.CharField(max_length=20)),
                ('OTP', models.IntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('deviceID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deviceToken', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='RFID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(default=uuid.uuid1, max_length=50, unique=True)),
                ('rfidUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machineID', models.CharField(default=uuid.uuid1, max_length=15, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('manufacture', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=10)),
                ('line', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='images/machineimages')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
        ),
    ]
