# Generated by Django 4.2.4 on 2024-07-18 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=45)),
                ('device_token', models.CharField(max_length=100)),
                ('hardware_version', models.CharField(blank=True, max_length=10, null=True)),
                ('software_version', models.CharField(blank=True, max_length=10, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('update_date_time', models.DateTimeField(auto_now=True)),
                ('protocol', models.CharField(max_length=10)),
                ('pub_topic', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_topic', models.CharField(blank=True, max_length=100, null=True)),
                ('api_path', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(default=uuid.uuid1, max_length=15, unique=True)),
                ('line', models.CharField(blank=True, max_length=30, null=True)),
                ('manufacture', models.CharField(blank=True, max_length=45, null=True)),
                ('year', models.CharField(blank=True, max_length=30, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('update_date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftTimings',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('shift_name', models.CharField(max_length=45)),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('update_date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='machine',
            name='device',
        ),
    ]
