# Generated by Django 4.2.4 on 2024-07-18 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventgroup_machines'),
        ('devices', '0002_devicedetails_machinedetails_machinegroup_and_more'),
        ('data', '0003_alter_lastproblemdata_deviceid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.AddField(
            model_name='machinegroup',
            name='machine_list',
            field=models.ManyToManyField(to='devices.machinedetails'),
        ),
        migrations.AddField(
            model_name='machinedetails',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicedetails'),
        ),
        migrations.AlterField(
            model_name='token',
            name='deviceID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deviceToken', to='devices.devicedetails'),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
