# Generated by Django 4.2.4 on 2024-07-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_devicedetails_device_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedetails',
            name='production_per_hour',
            field=models.IntegerField(default=0),
        ),
    ]
