# Generated by Django 4.2.4 on 2024-08-01 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_machinedetails_production_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttimings',
            name='shift_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='machinedetails',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.devicedetails'),
        ),
        migrations.AlterField(
            model_name='machinegroup',
            name='group_name',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='shifttimings',
            name='_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shifttimings',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shifttimings',
            name='shift_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='shifttimings',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
