# Generated by Django 4.2.4 on 2024-09-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_shifttiming'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedetails',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
