# Generated by Django 4.2.4 on 2024-10-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_machinedetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinedetails',
            name='offline_time',
            field=models.IntegerField(default=300),
        ),
    ]
