# Generated by Django 4.2.4 on 2024-09-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_machinedetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttiming',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
