# Generated by Django 4.2.4 on 2024-09-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_shifttiming_start_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttiming',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
