# Generated by Django 4.2.4 on 2024-10-14 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_machinedetails_offline_time'),
        ('devices', '0013_devicedetails_device_status'),
    ]

    operations = [
    ]
