# Generated by Django 4.2.4 on 2024-10-11 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(default='default_sid', max_length=100)),
                ('auth_token', models.CharField(default='default_auth_token', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMSNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smsnumber', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SendReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('to_number', models.CharField(max_length=15)),
                ('message', models.TextField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('delivery_status', models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('from_number', models.ForeignKey(on_delete=models.SET('Number deleted..'), to='smsgateway.smsnumber')),
            ],
        ),
    ]
