# Generated by Django 4.2.4 on 2024-07-16 07:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('data', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('deviceID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('eventGroupID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.eventgroup')),
                ('eventID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('machineID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.machine')),
            ],
        ),
        migrations.CreateModel(
            name='ProblemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('issueTime', models.DateTimeField()),
                ('acknowledgeTime', models.DateTimeField(blank=True, null=True)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('dateTimeNow', models.DateTimeField(auto_now=True)),
                ('deviceID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('eventGroupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventgroup')),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('machineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.machine')),
                ('rfidTime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.rfid')),
            ],
        ),
        migrations.CreateModel(
            name='LastProblemData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('issueTime', models.DateTimeField(blank=True, null=True)),
                ('acknowledgeTime', models.DateTimeField(blank=True, null=True)),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('dateTimeNow', models.DateTimeField(auto_now_add=True)),
                ('deviceID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
                ('eventGroupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventgroup')),
                ('eventID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('machineID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.machine')),
                ('rfidTime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.rfid')),
            ],
        ),
    ]
