# Generated by Django 4.2.4 on 2024-07-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('data', models.JSONField()),
                ('protocol', models.CharField(blank=True, max_length=10, null=True)),
                ('topic_api', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('update_date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('received_data', models.CharField(blank=True, max_length=2000, null=True)),
                ('protocol', models.CharField(blank=True, max_length=15, null=True)),
                ('topic_api', models.CharField(blank=True, max_length=100, null=True)),
                ('unique_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MachineData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('data', models.JSONField()),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('update_date_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('shift_name', models.CharField(max_length=45)),
                ('shift_start_time', models.TimeField()),
                ('shift_end_time', models.TimeField()),
                ('target_production', models.IntegerField()),
                ('machine_name', models.CharField(max_length=45)),
                ('production_count', models.IntegerField()),
            ],
        ),
    ]
