# Generated by Django 4.2.4 on 2024-07-18 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_devicedata_logdata_machinedata_productiondata'),
        ('devices', '0002_devicedetails_machinedetails_machinegroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastproblemdata',
            name='deviceID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.devicedetails'),
        ),
        migrations.AlterField(
            model_name='lastproblemdata',
            name='machineID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.machinedetails'),
        ),
        migrations.AlterField(
            model_name='problemdata',
            name='deviceID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.devicedetails'),
        ),
        migrations.AlterField(
            model_name='problemdata',
            name='machineID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.machinedetails'),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='deviceID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.devicedetails'),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='machineID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.machinedetails'),
        ),
        migrations.AddField(
            model_name='productiondata',
            name='data_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.logdata'),
        ),
        migrations.AddField(
            model_name='productiondata',
            name='machine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.machinedetails'),
        ),
        migrations.AddField(
            model_name='productiondata',
            name='shift_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.shifttimings'),
        ),
        migrations.AddField(
            model_name='machinedata',
            name='data_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.logdata'),
        ),
        migrations.AddField(
            model_name='machinedata',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicedetails'),
        ),
        migrations.AddField(
            model_name='machinedata',
            name='machine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.machinedetails'),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicedetails'),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='log_data_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.logdata'),
        ),
    ]
