# Generated by Django 4.2.4 on 2024-07-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_lastproblemdata_deviceid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiondata',
            name='data_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='machine_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='shift_id',
            field=models.IntegerField(),
        ),
    ]
