# Generated by Django 4.2.4 on 2024-07-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_productiondata_data_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiondata',
            name='machine_id',
            field=models.CharField(max_length=45),
        ),
    ]
