# Generated by Django 4.2.4 on 2024-08-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_productiondata_machine_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logdata',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='productiondata',
            name='shift_end_time',
        ),
        migrations.RemoveField(
            model_name='productiondata',
            name='shift_id',
        ),
        migrations.RemoveField(
            model_name='productiondata',
            name='shift_start_time',
        ),
        migrations.AddField(
            model_name='devicedata',
            name='timestamp',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='logdata',
            name='data_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='machinedata',
            name='timestamp',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productiondata',
            name='production_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='productiondata',
            name='shift_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productiondata',
            name='shift_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
