# Generated by Django 4.2.4 on 2024-08-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_logdata_unique_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machinedata',
            old_name='data_id',
            new_name='log_data_id',
        ),
        migrations.RenameField(
            model_name='productiondata',
            old_name='data_id',
            new_name='log_data_id',
        ),
        migrations.AddField(
            model_name='productiondata',
            name='timestamp',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
