# Generated by Django 4.2.4 on 2024-08-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_rename_data_id_machinedata_log_data_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdata',
            name='data_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
