# Generated by Django 4.2.4 on 2024-08-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_logdata_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinedata',
            name='timestamp',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
