# Generated by Django 4.2.4 on 2024-08-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_machinedata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productiondata',
            name='timestamp',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
