# Generated by Django 4.2.4 on 2024-08-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_alter_productiondata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='timestamp',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
