# Generated by Django 4.2.4 on 2024-09-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_alter_devicedata_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashbaordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('dashbaordData', models.JSONField()),
            ],
        ),
    ]
