# Generated by Django 4.2.4 on 2024-09-18 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_dashbaorddata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionUpdateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('production_data', models.JSONField()),
            ],
        ),
    ]
