# Generated by Django 4.2.4 on 2024-09-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_productionupdatedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionupdatedata',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='productionupdatedata',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
