# Generated by Django 4.2.4 on 2024-09-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_remove_productionupdatedata_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionupdatedata',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
