# Generated by Django 4.2.4 on 2024-09-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_productionupdatedata_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionupdatedata',
            name='date',
            field=models.DateField(),
        ),
    ]
