# Generated by Django 4.2.4 on 2024-10-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_alter_productionupdatedata_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdata',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
