# Generated by Django 4.2.4 on 2024-07-16 07:52

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unAuth_user_expiry_time', models.IntegerField(default=900)),
                ('all_user_expiry_time', models.IntegerField(default=86400)),
                ('OTP_resend_interval', models.IntegerField(default=20)),
                ('OTP_valid_time', models.IntegerField(default=600)),
                ('OTP_call_count', models.IntegerField(default=5)),
                ('OTP_wrong_count', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='UnauthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=15)),
                ('createdatetime', models.DateTimeField(auto_now_add=True)),
                ('otp', models.CharField(blank=True, max_length=5, null=True)),
                ('emailaddress', models.EmailField(max_length=254)),
                ('session_id', models.UUIDField(unique=True)),
                ('device_id', models.CharField(max_length=50)),
                ('otp_called', models.IntegerField(default=0)),
                ('designation', models.CharField(blank=True, max_length=15, null=True)),
                ('is_existing_user', models.BooleanField(default=False)),
                ('verification_token', models.UUIDField(blank=True, null=True, unique=True)),
                ('otp_wrong_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=15, null=True)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('auth_state', models.IntegerField(default=0)),
                ('expiry_time', models.IntegerField(default=86400)),
                ('extUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
