# Generated by Django 4.2.4 on 2024-07-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='device_id',
            new_name='employee_id',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='auth_state',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='expiry_time',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='registered_status',
            field=models.BooleanField(default=False),
        ),
    ]
