# Generated by Django 4.2.4 on 2024-07-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauth', '0002_rename_device_id_userdetail_employee_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='device_id',
            field=models.CharField(default='523758754', max_length=15, unique=True),
        ),
    ]
