# Generated by Django 4.2.4 on 2024-07-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauth', '0003_userdetail_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='device_id',
            field=models.CharField(default='523758754', max_length=15),
        ),
    ]
