# Generated by Django 4.2.4 on 2024-07-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauth', '0007_alter_userdetail_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='device_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
