# Generated by Django 4.2.4 on 2024-07-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userauth', '0008_alter_userdetail_device_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='device_id',
            new_name='Device_id',
        ),
    ]
