# Generated by Django 4.2.4 on 2024-07-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauth', '0010_rename_device_id_userdetail_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='device_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
