# Generated by Django 4.2.4 on 2024-07-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauth', '0011_alter_userdetail_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='employee_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
