# Generated by Django 4.2.4 on 2024-09-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userauth', '0012_alter_userdetail_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unauthuser',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='designation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
